import dotenv from 'dotenv';
dotenv.config({ path: new URL('../../.env', import.meta.url).pathname.slice(1) });
import mongoose from 'mongoose';
import Disease from '../models/Disease.js';

const diseases = [
    { name: 'Rice Blast', cropTypes: ['Rice'], symptoms: ['spots on leaves', 'diamond shaped lesions', 'gray center spots', 'neck rotting', 'panicle blast', 'dry leaves'], description: 'Fungal disease causing gray-green lesions on leaves', causes: ['Magnaporthe oryzae fungus', 'high nitrogen', 'humid conditions'], treatments: { organic: ['Neem oil 3ml/L', 'Trichoderma viride spray', 'Pseudomonas fluorescens'], chemical: ['Tricyclazole 75WP @ 0.6g/L', 'Isoprothiolane 40EC @ 1.5ml/L', 'Carbendazim 50WP @ 1g/L'], preventive: ['Use resistant varieties', 'Avoid excess nitrogen', 'Proper spacing'] }, severity: 'high', spreadRisk: 'high', season: 'kharif', climateConditions: { minTempC: 20, maxTempC: 30, humidityAbovePct: 90 } },
    { name: 'Brown Spot', cropTypes: ['Rice'], symptoms: ['brown oval spots', 'yellow halo around spots', 'leaf browning', 'grain discoloration', 'seedling blight'], description: 'Fungal disease causing brown spots on rice leaves', causes: ['Bipolaris oryzae', 'nutrient deficiency', 'poor soil'], treatments: { organic: ['Trichoderma application', 'Neem cake in soil', 'Compost tea spray'], chemical: ['Mancozeb 75WP @ 2g/L', 'Propiconazole 25EC @ 1ml/L', 'Zineb 75WP @ 2g/L'], preventive: ['Balanced fertilization', 'Potassium application', 'Seed treatment'] }, severity: 'medium', spreadRisk: 'medium', season: 'kharif', climateConditions: { minTempC: 25, maxTempC: 35, humidityAbovePct: 80 } },
    { name: 'Bacterial Leaf Blight', cropTypes: ['Rice'], symptoms: ['water-soaked streaks', 'yellow to white lesions', 'wilting seedlings', 'milky ooze from cut leaves', 'leaf drying from tip'], description: 'Bacterial disease causing leaf blight in rice', causes: ['Xanthomonas oryzae', 'contaminated water', 'wounds'], treatments: { organic: ['Copper hydroxide spray', 'Neem oil', 'Streptocycline 0.5g/L'], chemical: ['Streptomycin sulphate + Tetracycline', 'Copper oxychloride 50WP @ 3g/L', 'Plantomycin 1g/L'], preventive: ['Resistant varieties like Swarna', 'Avoid nitrogen excess', 'Clean field drainage'] }, severity: 'high', spreadRisk: 'high', season: 'kharif', climateConditions: { minTempC: 25, maxTempC: 34, humidityAbovePct: 85 } },
    { name: 'Sheath Blight', cropTypes: ['Rice'], symptoms: ['oval greenish-gray lesions on sheath', 'irregular spots', 'sheath rotting', 'lodging', 'sclerotia on surface'], description: 'Fungal disease affecting rice sheaths', causes: ['Rhizoctonia solani', 'dense planting', 'high humidity'], treatments: { organic: ['Trichoderma harzianum', 'Neem oil spray', 'Bio-agents'], chemical: ['Hexaconazole 5EC @ 2ml/L', 'Validamycin 3L @ 2ml/L', 'Propiconazole 25EC @ 1ml/L'], preventive: ['Proper spacing', 'Avoid high nitrogen', 'Clean cultivation'] }, severity: 'high', spreadRisk: 'medium', season: 'kharif', climateConditions: { minTempC: 28, maxTempC: 35, humidityAbovePct: 85 } },
    { name: 'False Smut', cropTypes: ['Rice'], symptoms: ['yellow-green spore balls on panicle', 'velvety covering on grains', 'orange-yellow mass', 'affected grains enlarge', 'smutted grains'], description: 'Fungal disease producing spore balls on rice grains', causes: ['Ustilaginoidea virens', 'excessive nitrogen', 'late sowing'], treatments: { organic: ['Neem seed kernel extract', 'Bio-agents', 'Organic soil amendments'], chemical: ['Propiconazole 25EC @ 1ml/L', 'Copper oxychloride 50WP', 'Carbendazim spray at booting'], preventive: ['Balanced fertilization', 'Timely sowing', 'Seed treatment'] }, severity: 'medium', spreadRisk: 'low', season: 'kharif', climateConditions: { minTempC: 25, maxTempC: 32, humidityAbovePct: 90 } },
    { name: 'Yellow Rust', cropTypes: ['Wheat'], symptoms: ['yellow stripes on leaves', 'powdery yellow pustules', 'parallel streaks', 'leaf yellowing', 'premature drying'], description: 'Stripe rust causing yellow pustules in rows on wheat', causes: ['Puccinia striiformis', 'cool moist weather', 'susceptible varieties'], treatments: { organic: ['Sulfur dust spray', 'Neem oil', 'Trichoderma viride'], chemical: ['Propiconazole 25EC @ 1ml/L', 'Tebuconazole 25.9EC @ 1ml/L', 'Mancozeb 75WP @ 2g/L'], preventive: ['Resistant varieties like HD-2967', 'Timely sowing', 'Avoid late irrigation'] }, severity: 'high', spreadRisk: 'high', season: 'rabi', climateConditions: { minTempC: 10, maxTempC: 20, humidityAbovePct: 70 } },
    { name: 'Brown Rust', cropTypes: ['Wheat'], symptoms: ['orange-brown circular pustules', 'scattered on leaves', 'leaf surfaces turning brown', 'premature leaf death', 'reduced grain filling'], description: 'Leaf rust causing brown pustules scattered on wheat leaves', causes: ['Puccinia triticina', 'warm moist conditions'], treatments: { organic: ['Neem oil spray', 'Bio-control agents'], chemical: ['Propiconazole 25EC @ 1ml/L', 'Tebuconazole', 'Mancozeb spray'], preventive: ['Grow resistant varieties', 'Timely sowing in November'] }, severity: 'medium', spreadRisk: 'high', season: 'rabi', climateConditions: { minTempC: 15, maxTempC: 25, humidityAbovePct: 75 } },
    { name: 'Black Rust', cropTypes: ['Wheat'], symptoms: ['dark brown to black pustules', 'stem lesions', 'sheath infection', 'broken epidermis', 'lodging'], description: 'Stem rust causing black pustules on wheat stems', causes: ['Puccinia graminis', 'warm humid weather late season'], treatments: { organic: ['Remove alternate host Berberis', 'Bio-control'], chemical: ['Propiconazole 25EC', 'Mancozeb 75WP @ 2.5g/L', 'Oxycarboxin 75WP'], preventive: ['Resistant varieties', 'Early sowing', 'Destroy infected debris'] }, severity: 'critical', spreadRisk: 'high', season: 'rabi', climateConditions: { minTempC: 18, maxTempC: 30, humidityAbovePct: 80 } },
    { name: 'Powdery Mildew', cropTypes: ['Wheat', 'Tomato', 'Onion'], symptoms: ['white powdery coating', 'leaf curling', 'yellowing of leaves', 'stunted growth', 'premature leaf fall'], description: 'White powdery fungal growth on leaves and stems', causes: ['Erysiphe graminis', 'high humidity', 'crowded planting'], treatments: { organic: ['Sulfur dust @ 25kg/ha', 'Neem oil 3ml/L', 'Milk spray 1:9 ratio'], chemical: ['Karathane 48EC @ 1ml/L', 'Triadimefon 25WP @ 0.5g/L', 'Sulfur 80WP @ 3g/L'], preventive: ['Good air circulation', 'Avoid excess nitrogen', 'Resistant varieties'] }, severity: 'medium', spreadRisk: 'medium', season: 'rabi', climateConditions: { minTempC: 15, maxTempC: 28, humidityAbovePct: 65 } },
    { name: 'Karnal Bunt', cropTypes: ['Wheat'], symptoms: ['fishy smell from grains', 'black powder in grains', 'partially converted kernels', 'foul odor', 'darkened grain tip'], description: 'Smut disease converting wheat grain interior to black powder', causes: ['Tilletia indica', 'cool wet weather at flowering'], treatments: { organic: ['Hot water seed treatment', 'Bio-agents'], chemical: ['Thiram + Carbendazim seed treatment', 'Propiconazole spray at boot stage'], preventive: ['Certified seed', 'Avoid late sowing', 'Crop rotation'] }, severity: 'medium', spreadRisk: 'low', season: 'rabi', climateConditions: { minTempC: 15, maxTempC: 22, humidityAbovePct: 80 } },
    { name: 'Loose Smut', cropTypes: ['Wheat'], symptoms: ['black dusty spore mass replacing grains', 'naked rachis', 'early heading', 'black panicles', 'spore dispersal by wind'], description: 'Smut replacing entire wheat head with black spores', causes: ['Ustilago tritici', 'internally seed-borne'], treatments: { organic: ['Solar seed treatment', 'Hot water treatment 52°C for 10 min'], chemical: ['Carboxin 75WP seed treatment @ 2g/kg', 'Vitavax 75WP', 'Thiram seed treatment'], preventive: ['Certified disease-free seed', 'Seed treatment mandatory'] }, severity: 'medium', spreadRisk: 'medium', season: 'rabi', climateConditions: { minTempC: 15, maxTempC: 25, humidityAbovePct: 70 } },
    { name: 'Cotton Bollworm', cropTypes: ['Cotton'], symptoms: ['bore holes in bolls', 'frass on bolls', 'damaged squares', 'shedding of flowers', 'reduced boll formation'], description: 'Helicoverpa armigera larvae boring into cotton bolls', causes: ['Helicoverpa armigera moth', 'warm weather', 'late season crop'], treatments: { organic: ['Neem seed kernel extract 5%', 'HaNPV virus @ 250LE/ha', 'Trichogramma egg parasitoid release'], chemical: ['Emamectin benzoate 5SG @ 0.4g/L', 'Chlorantraniliprole 18.5SC @ 0.3ml/L', 'Indoxacarb 14.5SC @ 1ml/L'], preventive: ['Bt cotton varieties', 'Pheromone traps', 'Early sowing'] }, severity: 'critical', spreadRisk: 'high', season: 'kharif', climateConditions: { minTempC: 25, maxTempC: 38, humidityAbovePct: 60 } },
    { name: 'Cotton Leaf Curl Virus', cropTypes: ['Cotton'], symptoms: ['upward curling of leaves', 'thickened veins', 'cup-shaped leaves', 'stunted plants', 'enation on underside'], description: 'Viral disease transmitted by whitefly causing leaf curling', causes: ['Begomovirus', 'transmitted by Bemisia tabaci whitefly'], treatments: { organic: ['Yellow sticky traps', 'Neem oil 3ml/L', 'Remove infected plants'], chemical: ['Imidacloprid 17.8SL @ 0.3ml/L (for whitefly)', 'Thiamethoxam 25WG', 'Acetamiprid 20SP @ 0.3g/L'], preventive: ['Resistant varieties', 'Whitefly management', 'Avoid ratoon crop'] }, severity: 'high', spreadRisk: 'high', season: 'kharif', climateConditions: { minTempC: 25, maxTempC: 40, humidityAbovePct: 50 } },
    { name: 'Cotton Root Rot', cropTypes: ['Cotton'], symptoms: ['sudden wilting', 'brown root system', 'leaf yellowing', 'plant death', 'bark peeling on roots'], description: 'Soil-borne fungal disease killing cotton roots', causes: ['Macrophomina phaseolina', 'drought stress', 'hot soil'], treatments: { organic: ['Trichoderma soil application @ 4kg/ha', 'Neem cake', 'FYM enriched with bio-agents'], chemical: ['Carbendazim soil drench', 'Carboxin seed treatment', 'Copper oxychloride 50WP'], preventive: ['Deep summer ploughing', 'Crop rotation', 'Soil solarization'] }, severity: 'high', spreadRisk: 'low', season: 'kharif', climateConditions: { minTempC: 30, maxTempC: 40, humidityAbovePct: 40 } },
    { name: 'Alternaria Leaf Spot', cropTypes: ['Cotton', 'Tomato'], symptoms: ['circular brown spots', 'concentric rings on spots', 'leaf yellowing around spots', 'defoliation', 'dark spots on stems'], description: 'Fungal disease causing target-board pattern spots', causes: ['Alternaria macrospora', 'warm humid conditions'], treatments: { organic: ['Neem oil spray', 'Trichoderma application', 'Copper soap spray'], chemical: ['Mancozeb 75WP @ 2.5g/L', 'Chlorothalonil 75WP @ 2g/L', 'Iprodione 50WP'], preventive: ['Remove crop debris', 'Avoid overhead irrigation', 'Proper spacing'] }, severity: 'medium', spreadRisk: 'medium', season: 'all', climateConditions: { minTempC: 25, maxTempC: 32, humidityAbovePct: 75 } },
    { name: 'Early Blight', cropTypes: ['Tomato'], symptoms: ['dark concentric ring spots', 'target board appearance', 'lower leaf infection first', 'defoliation from bottom', 'collar rot in seedlings'], description: 'Common fungal disease of tomato causing target-like spots', causes: ['Alternaria solani', 'warm wet weather', 'poor nutrition'], treatments: { organic: ['Trichoderma spray', 'Neem oil', 'Compost tea'], chemical: ['Mancozeb 75WP @ 2.5g/L', 'Chlorothalonil @ 2g/L', 'Azoxystrobin 23SC @ 1ml/L'], preventive: ['Crop rotation', 'Staking plants', 'Remove lower leaves'] }, severity: 'medium', spreadRisk: 'medium', season: 'all', climateConditions: { minTempC: 20, maxTempC: 30, humidityAbovePct: 70 } },
    { name: 'Late Blight', cropTypes: ['Tomato'], symptoms: ['water-soaked dark patches', 'white fungal growth under leaf', 'rapid browning', 'fruit rot', 'foul smell'], description: 'Devastating oomycete disease causing rapid plant death', causes: ['Phytophthora infestans', 'cool wet weather', 'foggy conditions'], treatments: { organic: ['Copper-based fungicides', 'Bordeaux mixture 1%', 'Remove infected parts'], chemical: ['Metalaxyl + Mancozeb (Ridomil MZ) @ 2g/L', 'Cymoxanil + Mancozeb', 'Fenamidone + Mancozeb'], preventive: ['Resistant varieties', 'Good drainage', 'Avoid evening irrigation'] }, severity: 'critical', spreadRisk: 'high', season: 'rabi', climateConditions: { minTempC: 10, maxTempC: 22, humidityAbovePct: 85 } },
    { name: 'Tomato Leaf Curl', cropTypes: ['Tomato'], symptoms: ['upward curling of leaves', 'yellowing margins', 'stunted growth', 'thickened veins', 'no fruit formation'], description: 'Viral disease spread by whitefly causing severe yield loss', causes: ['Tomato Leaf Curl Virus (ToLCV)', 'Bemisia tabaci vector'], treatments: { organic: ['Yellow sticky traps 12/acre', 'Neem oil 5ml/L', 'Destroy infected plants'], chemical: ['Imidacloprid 17.8SL @ 0.3ml/L', 'Thiamethoxam 25WG @ 0.3g/L', 'Spiromesifen 22.9SC'], preventive: ['Whitefly-free nursery', 'Silver mulch', 'Resistant varieties like Arka Rakshak'] }, severity: 'high', spreadRisk: 'high', season: 'all', climateConditions: { minTempC: 25, maxTempC: 38, humidityAbovePct: 50 } },
    { name: 'Damping Off', cropTypes: ['Tomato', 'Onion'], symptoms: ['seedling collapse', 'water-soaked stem base', 'thin rotted stem', 'seedling death before emergence', 'patches in nursery'], description: 'Soil-borne disease killing seedlings at nursery stage', causes: ['Pythium / Rhizoctonia', 'overwatering', 'poor drainage'], treatments: { organic: ['Trichoderma viride seed treatment', 'Pseudomonas fluorescens', 'Well-drained raised beds'], chemical: ['Metalaxyl (Ridomil) @ 2g/L drench', 'Captan 50WP seed treatment @ 3g/kg', 'Thiram 75WP'], preventive: ['Raised nursery beds', 'Avoid overwatering', 'Soil solarization'] }, severity: 'medium', spreadRisk: 'low', season: 'all', climateConditions: { minTempC: 15, maxTempC: 30, humidityAbovePct: 85 } },
    { name: 'Fusarium Wilt', cropTypes: ['Tomato', 'Cotton', 'Chickpea'], symptoms: ['one-sided wilting', 'yellowing of lower leaves', 'brown vascular bundles', 'plant wilting on hot days', 'stunted growth'], description: 'Soil-borne vascular wilt disease', causes: ['Fusarium oxysporum', 'acidic soils', 'warm soil temperatures'], treatments: { organic: ['Trichoderma viride @ 4kg/ha', 'Pseudomonas fluorescens', 'Neem cake application'], chemical: ['Carbendazim 50WP soil drench @ 1g/L', 'Thiophanate methyl', 'Benomyl 50WP'], preventive: ['Resistant varieties', 'Crop rotation 3-4 years', 'Lime application for pH correction'] }, severity: 'high', spreadRisk: 'low', season: 'all', climateConditions: { minTempC: 24, maxTempC: 34, humidityAbovePct: 60 } },
    { name: 'Downy Mildew (Maize)', cropTypes: ['Maize'], symptoms: ['white downy growth on underleaf', 'chlorotic streaks', 'stunted cobs', 'leafy inflorescence', 'crazy top symptom'], description: 'Oomycete disease causing white downy patches', causes: ['Peronosclerospora sorghi', 'high humidity', 'infected soil'], treatments: { organic: ['Remove infected plants', 'Bio-agents', 'Organic soil amendments'], chemical: ['Metalaxyl 35SD @ 6g/kg seed treatment', 'Metalaxyl + Mancozeb spray', 'Fosetyl-Al'], preventive: ['Resistant hybrids', 'Seed treatment mandatory', 'Avoid waterlogging'] }, severity: 'high', spreadRisk: 'medium', season: 'kharif', climateConditions: { minTempC: 20, maxTempC: 30, humidityAbovePct: 90 } },
    { name: 'Turcicum Leaf Blight', cropTypes: ['Maize'], symptoms: ['long elliptical gray-green lesions', 'lesions 3-15cm long', 'blighting from lower leaves', 'cigar-shaped spots', 'heavy defoliation'], description: 'Major foliar disease of maize in India', causes: ['Exserohilum turcicum', 'cool moist conditions'], treatments: { organic: ['Trichoderma spray', 'Neem oil', 'Remove debris'], chemical: ['Mancozeb 75WP @ 2.5g/L', 'Zineb 75WP', 'Propiconazole 25EC @ 1ml/L'], preventive: ['Resistant hybrids', 'Timely sowing', 'Balanced fertilization'] }, severity: 'medium', spreadRisk: 'medium', season: 'kharif', climateConditions: { minTempC: 18, maxTempC: 27, humidityAbovePct: 80 } },
    { name: 'Maize Stalk Rot', cropTypes: ['Maize'], symptoms: ['stalk breaking at nodes', 'soft rotted internodes', 'premature drying', 'hollow stem', 'white to pink mold inside'], description: 'Complex of fungi causing stalk rot and lodging', causes: ['Fusarium/Macrophomina', 'drought stress followed by rain', 'nutrient deficiency'], treatments: { organic: ['Trichoderma soil treatment', 'FYM application', 'Bio-fertilizers'], chemical: ['Carbendazim 50WP seed treatment', 'Thiram seed treatment', 'Propiconazole spray'], preventive: ['Balanced potassium fertilization', 'Avoid water stress', 'Proper plant population'] }, severity: 'high', spreadRisk: 'low', season: 'kharif', climateConditions: { minTempC: 25, maxTempC: 35, humidityAbovePct: 70 } },
    { name: 'Corn Smut', cropTypes: ['Maize'], symptoms: ['large galls on ears', 'silver-white swellings', 'galls on tassels', 'greenish-white tumor-like growths', 'black spore mass inside galls'], description: 'Fungal disease forming tumor-like galls filled with spores', causes: ['Ustilago maydis', 'mechanical injury', 'hailstorm damage'], treatments: { organic: ['Remove galls before spore release', 'Resistant varieties', 'Deep ploughing'], chemical: ['Propiconazole preventive spray', 'No effective chemical control after infection'], preventive: ['Avoid mechanical damage', 'Grow resistant hybrids', 'Destroy galls'] }, severity: 'medium', spreadRisk: 'low', season: 'kharif', climateConditions: { minTempC: 25, maxTempC: 34, humidityAbovePct: 70 } },
    { name: 'Purple Blotch', cropTypes: ['Onion'], symptoms: ['purple-brown oval lesions', 'concentric rings on spots', 'leaf tip dieback', 'alternating light and dark zones', 'neck infection'], description: 'Major fungal disease of onion in India', causes: ['Alternaria porri', 'warm humid weather', 'late season crop'], treatments: { organic: ['Trichoderma application', 'Neem oil spray', 'Mancozeb organic alternatives'], chemical: ['Mancozeb 75WP @ 2.5g/L', 'Chlorothalonil 75WP @ 2g/L', 'Iprodione + Carbendazim'], preventive: ['Proper spacing', 'Morning irrigation only', 'Remove debris after harvest'] }, severity: 'high', spreadRisk: 'medium', season: 'rabi', climateConditions: { minTempC: 20, maxTempC: 30, humidityAbovePct: 80 } },
    { name: 'Stemphylium Blight', cropTypes: ['Onion'], symptoms: ['small yellow to brown spots', 'elongated lesions', 'leaf blade tip death', 'water-soaked areas', 'rapid drying of leaves'], description: 'Fungal disease causing rapid leaf drying in onion', causes: ['Stemphylium vesicarium', 'humid conditions', 'injury by thrips'], treatments: { organic: ['Trichoderma spray', 'Organic sulfur dust', 'Bio-control agents'], chemical: ['Mancozeb 75WP @ 2.5g/L', 'Hexaconazole 5EC @ 2ml/L', 'Chlorothalonil 75WP'], preventive: ['Thrips management crucial', 'Avoid dense planting', 'Drainage improvement'] }, severity: 'medium', spreadRisk: 'medium', season: 'rabi', climateConditions: { minTempC: 20, maxTempC: 30, humidityAbovePct: 85 } },
    { name: 'Onion Downy Mildew', cropTypes: ['Onion'], symptoms: ['pale green to yellow patches', 'violet-gray fuzzy growth', 'leaf collapse', 'bulb rot in severe cases', 'seedstalk infection'], description: 'Oomycete disease causing downy growth on onion leaves', causes: ['Peronospora destructor', 'cool wet mornings', 'foggy weather'], treatments: { organic: ['Copper hydroxide spray', 'Good air flow management', 'Remove infected plants'], chemical: ['Metalaxyl + Mancozeb (Ridomil MZ) @ 2g/L', 'Cymoxanil + Mancozeb', 'Fosetyl-Al'], preventive: ['Avoid low-lying waterlogged fields', 'Proper spacing', 'Morning harvest of dew-covered fields'] }, severity: 'high', spreadRisk: 'high', season: 'rabi', climateConditions: { minTempC: 10, maxTempC: 22, humidityAbovePct: 90 } },
    { name: 'Chickpea Wilt', cropTypes: ['Chickpea'], symptoms: ['sudden wilting', 'yellowing and drooping', 'brown discoloration of roots', 'plant death within days', 'disease appears in patches'], description: 'Soil-borne wilt disease devastating chickpea', causes: ['Fusarium oxysporum f.sp. ciceri', 'warm soil', 'acidic pH'], treatments: { organic: ['Trichoderma viride seed treatment @ 4g/kg', 'Pseudomonas fluorescens', 'Neem cake'], chemical: ['Carbendazim + Thiram seed treatment @ 2g/kg', 'Carboxin 37.5% + Thiram 37.5% WP'], preventive: ['Resistant varieties like JG-62', 'Deep summer ploughing', '3-year crop rotation'] }, severity: 'high', spreadRisk: 'low', season: 'rabi', climateConditions: { minTempC: 20, maxTempC: 30, humidityAbovePct: 50 } },
    { name: 'Chickpea Blight (Ascochyta)', cropTypes: ['Chickpea'], symptoms: ['circular brown lesions on leaves', 'dark concentric spots on pods', 'stem girdle breakage', 'seed discoloration', 'premature drying'], description: 'Major fungal disease of chickpea', causes: ['Ascochyta rabiei', 'prolonged rainfall', 'cool weather'], treatments: { organic: ['Seed treatment with bio-agents', 'Remove infected debris', 'Bordeaux mixture spray'], chemical: ['Mancozeb 75WP @ 2g/L', 'Chlorothalonil 75WP @ 2g/L', 'Carbendazim 50WP @ 1g/L'], preventive: ['Resistant cultivars', 'Clean seed', 'Wide spacing 30x10cm'] }, severity: 'high', spreadRisk: 'high', season: 'rabi', climateConditions: { minTempC: 10, maxTempC: 20, humidityAbovePct: 80 } },
    { name: 'Chickpea Root Rot', cropTypes: ['Chickpea'], symptoms: ['yellowing and drying of lower leaves', 'rotted roots', 'black discoloration at collar region', 'plant topples easily', 'scattered dying plants'], description: 'Soil-borne root disease of chickpea', causes: ['Rhizoctonia solani / Macrophomina', 'wet followed by dry conditions'], treatments: { organic: ['Trichoderma harzianum application', 'Bio-priming of seeds', 'FYM enrichment'], chemical: ['Thiram 75WP seed treatment @ 3g/kg', 'Carbendazim 50WP soil drench', 'Vitavax 75WP'], preventive: ['Avoid waterlogging', 'Deep summer ploughing', 'Crop rotation with cereals'] }, severity: 'medium', spreadRisk: 'low', season: 'rabi', climateConditions: { minTempC: 20, maxTempC: 30, humidityAbovePct: 60 } },
];

export async function runSeed() {
    const count = await Disease.countDocuments();
    if (count > 0) {
        console.log(`⏭  Diseases already seeded (${count} records). Skipping.`);
        return count;
    }
    await Disease.insertMany(diseases);
    console.log(`✅ Seeded ${diseases.length} diseases`);
    return diseases.length;
}

// Run standalone
if (process.argv[1]?.includes('seedDiseases')) {
    try {
        await mongoose.connect(process.env.MONGODB_URI);
        await runSeed();
        process.exit(0);
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
}
