import dotenv from 'dotenv';
dotenv.config({ path: new URL('../../.env', import.meta.url).pathname.slice(1) });
import mongoose from 'mongoose';
import Advisory from '../models/Advisory.js';

const advisories = [
    { title: 'Kharif Rice — Best Practices Guide', content: 'For successful Kharif rice cultivation, start nursery preparation in June with 20kg seed per acre. Transplant 25-day-old seedlings at 20x15cm spacing. Apply DAP 50kg/acre as basal dose. First top dressing with Urea 25kg/acre at 21 days after transplanting. Maintain 5cm standing water. Monitor for stem borer and blast disease. Use Tricyclazole preventive spray at panicle initiation.', category: 'best_practice', cropTypes: ['Rice'], season: 'kharif', source: 'ICAR-IIRR', tags: ['rice', 'kharif', 'transplanting'] },
    { title: 'Rabi Wheat Sowing Calendar', content: 'Optimal wheat sowing window: November 1-25 for northern India. Use HD-2967, PBW-343 for timely sown conditions. Seed rate: 40kg/acre. Apply DAP 50kg + MOP 20kg/acre basal. First irrigation at Crown Root Initiation (21 days). Total 5-6 irrigations needed. Watch for yellow rust if cool foggy weather persists. Spray Propiconazole at first sign of rust.', category: 'best_practice', cropTypes: ['Wheat'], season: 'rabi', source: 'ICAR-IARI New Delhi', tags: ['wheat', 'rabi', 'sowing'] },
    { title: 'Organic Pest Control for Tomato', content: 'Manage tomato pests organically: 1) Install Yellow sticky traps 12/acre for whitefly. 2) Spray Neem oil 5ml/L weekly. 3) Release Trichogramma chilonis for fruit borer @ 1 lakh/acre. 4) Use Beauveria bassiana for thrips. 5) Spray Pseudomonas fluorescens for bacterial wilt prevention. 6) Mulch with silver-colored plastic to repel whitefly. 7) Companion plant marigold to trap nematodes.', category: 'pest_control', cropTypes: ['Tomato'], season: 'all', source: 'KVK Hyderabad', tags: ['tomato', 'organic', 'pest'] },
    { title: 'Drip Irrigation Guide for Cotton', content: 'Cotton drip irrigation saves 40% water and increases yield by 25%. Layout: place drip laterals every 1.2m with emitters at 40cm spacing. Water requirement: 3-5 liters/plant/day in vegetative stage, 6-8 liters during flowering. Fertigation schedule: inject Urea 30kg/acre in 3 splits through drip. Apply 19:19:19 complex during flowering at 5kg/acre/week. Monitor soil moisture with tensiometer — irrigate when reading crosses 40 centibar.', category: 'best_practice', cropTypes: ['Cotton'], season: 'kharif', source: 'CICR Nagpur', tags: ['cotton', 'drip', 'irrigation'] },
    { title: 'PM-KISAN Scheme — Complete Guide', content: 'Pradhan Mantri Kisan Samman Nidhi provides ₹6,000/year in three installments of ₹2,000 each to all small and marginal farmer families. Eligibility: landholding families with cultivable land. Registration: visit pmkisan.gov.in or nearest CSC center. Documents needed: Aadhaar card, bank account, land records. Installments: Apr-Jul, Aug-Nov, Dec-Mar. Status check on same portal. Excluded: institutional landholders, former/current holders of constitutional posts, professionals with income tax liability.', category: 'scheme', season: 'all', source: 'Ministry of Agriculture', tags: ['pm-kisan', 'scheme', 'government', 'subsidy'] },
    { title: 'PM Fasal Bima Yojana — Crop Insurance', content: 'PMFBY provides insurance coverage against crop loss due to natural calamities. Premium: Kharif 2%, Rabi 1.5%, Horticultural 5% of sum insured. Coverage: prevented sowing, mid-season adversity, post-harvest losses (14 days), localized calamities. Apply before sowing deadline at bank/CSC. Claim process: intimate loss within 72 hours via app, crop cutting experiments determine payout. All crops eligible. Voluntary for non-loanee farmers since 2020.', category: 'scheme', season: 'all', source: 'Ministry of Agriculture', tags: ['pmfby', 'insurance', 'scheme'] },
    { title: 'eNAM — Electronic National Agriculture Market', content: 'eNAM connects 1000+ mandis across India for transparent online trading. Benefits: discover best prices nationwide, competitive bidding, direct payment to bank. How to use: register at enam.gov.in with Aadhaar + bank details. Upload produce details, get lot number, quality tested at mandi. Buyers bid online — highest bid wins. Payment within T+1 day via RTGS. Currently covers: cereals, pulses, oilseeds, fruits, vegetables. No registration fee for farmers.', category: 'scheme', season: 'all', source: 'Ministry of Agriculture', tags: ['enam', 'market', 'mandi'] },
    { title: 'Water Conservation Tips for Rainfed Farms', content: 'Conserve water in rainfed areas: 1) Build farm ponds to capture runoff — minimum 10x10x3m. 2) Contour bunding for slopes >2%. 3) Use drought-tolerant varieties: Sahbhagi Dhan (rice), C-306 (wheat). 4) Apply mulch 5cm thick — reduces evaporation 30%. 5) Practice ridge-furrow method for row crops. 6) Install micro-irrigation for high-value crops. 7) Broad Bed Furrow (BBF) system for black soils. Government subsidizes 80% cost for farm ponds under PMKSY.', category: 'best_practice', season: 'all', source: 'CRIDA Hyderabad', tags: ['water', 'conservation', 'rainfed'] },
    { title: 'Soil Testing — Why and How', content: 'Test soil every 2 years for optimal fertilization. Collect 15-20 sub-samples from field in V-pattern at 15cm depth. Mix, quarter, and send 500g to nearest Soil Testing Lab (free at KVK). Parameters tested: pH, EC, organic carbon, available N-P-K, micro-nutrients. Based on results: acidic soil (pH<6.5) — apply lime 2-5 quintal/acre. Alkaline (pH>8.5) — apply gypsum. Low OC — apply FYM 10ton/acre. Use Soil Health Card portal: soilhealth.dac.gov.in', category: 'best_practice', season: 'all', source: 'Soil Health Mission', tags: ['soil', 'testing', 'fertilizer'] },
    { title: 'Onion Storage — Reducing Post-Harvest Loss', content: 'Reduce onion storage losses from 25% to under 5%: 1) Cure onions in field for 3-5 days after harvest. 2) Cut tops leaving 2cm neck. 3) Grade — remove damaged/diseased bulbs. 4) Use bottom-ventilated storage structures with 1m height stacking. 5) Store on wooden platforms, not directly on floor. 6) Maintain 25-30°C, 65-70% humidity. 7) Inspect weekly for sprouting/rotting. 8) Use Maleic hydrazide spray 15 days before harvest to prevent sprouting. Cold storage at 0-2°C for long-term (6 months).', category: 'best_practice', cropTypes: ['Onion'], season: 'rabi', source: 'NHRDF Nashik', tags: ['onion', 'storage', 'post-harvest'] },
    { title: 'IPM Approach for Cotton', content: 'Integrated Pest Management for cotton: Economic Threshold Levels (ETL) — Bollworm: 1 larva/plant, Whitefly: 5-10/leaf, Jassid: 2/leaf. Start with cultural control: remove first-formed squares with eggs. Use pheromone traps for bollworm monitoring. Release Trichogramma @ 1.5 lakh/acre every 10 days. Spray Neem oil for sucking pests. Use chemical only above ETL. Rotate mode of action — do not repeat same insecticide within 14 days.', category: 'pest_control', cropTypes: ['Cotton'], season: 'kharif', source: 'CICR Nagpur', tags: ['cotton', 'ipm', 'pest'] },
    { title: 'Micro-Nutrient Deficiency Identification', content: 'Common micro-nutrient deficiency symptoms: Zinc: interveinal chlorosis on young leaves, stunting in rice — spray ZnSO4 0.5%. Iron: complete yellowing of young leaves — spray FeSO4 0.5% + citric acid 0.1%. Boron: thick brittle leaves, cracking in turnip/cauliflower — spray Borax 0.2%. Manganese: interveinal chlorosis on middle leaves — MnSO4 0.5%. Sulfur deficiency appears similar to nitrogen but on young leaves. Apply soil test-based micro-nutrients during final ploughing for best results.', category: 'best_practice', season: 'all', source: 'ICAR', tags: ['micronutrient', 'deficiency', 'nutrition'] },
    { title: 'Vermicompost Production at Farm Level', content: 'Setup vermicompost unit: 1) Build pit 3m x 1m x 0.5m under shade. 2) Layer bottom with 15cm crop residues + cowdung. 3) Introduce 1000 Eisenia fetida earthworms. 4) Maintain moisture 50-60% — water every 2 days. 5) Add kitchen/farm waste weekly in layers. 6) Turn pile monthly. 7) Harvest after 45-60 days when dark brown, earthy smell appears. 8) Yield: 600-700kg from 1 ton raw material. Apply 2-5 ton/acre. Contains 1.5% N, 0.5% P, 0.5% K plus enzymes and beneficial microbes.', category: 'best_practice', season: 'all', source: 'KVK Hyderabad', tags: ['vermicompost', 'organic', 'fertilizer'] },
    { title: 'Weather-Based Spray Scheduling', content: 'Maximize pesticide effectiveness with weather-based timing: 1) Best spray time: 7-10 AM when dew evaporates. 2) Avoid spraying if rain expected within 4 hours. 3) Wind speed must be below 15 km/h. 4) Humidity 50-70% is ideal for systemic products. 5) Do not spray during noon heat (12-3 PM) — rapid evaporation reduces efficacy. 6) Fungicide timing: spray BEFORE disease appears (preventive) or at first sign (curative). 7) Use sticker/spreader for waxy-leaf crops like onion, cabbage.', category: 'best_practice', season: 'all', source: 'MANAGE Hyderabad', tags: ['spray', 'weather', 'pesticide'] },
    { title: 'Kisan Credit Card — Benefits and Application', content: 'KCC provides credit up to ₹3 lakh at 4% interest (after government subsidy). Apply at any scheduled bank with: land records (passbook/patta), Aadhaar, income certificate. Credit limit based on land area and crop. Repayment within 12 months gets 3% interest subvention (effective rate 4%). Can withdraw from any ATM. Also covers: term loans for agri equipment, working capital for allied activities (dairy, fishery). Crop insurance under PMFBY linked to KCC. No collateral needed up to ₹1.6 lakh.', category: 'scheme', season: 'all', source: 'NABARD', tags: ['kcc', 'credit', 'loan', 'bank'] },
    { title: 'Precision Nitrogen Management in Rice', content: 'Avoid over-application of Urea: use Leaf Color Chart (LCC) for need-based nitrogen management. Compare rice leaf color with LCC readings — apply Urea only when LCC reading falls below 4. Split nitrogen into 3-4 doses: basal 25%, tillering 25%, panicle initiation 30%, flowering 20%. Use neem-coated urea for 10% better efficiency. Excess nitrogen causes: blast disease, lodging, reduced grain quality, and environmental pollution. Target: 120-150 kg N/ha for high-yielding varieties.', category: 'best_practice', cropTypes: ['Rice'], season: 'kharif', source: 'ICAR-IIRR', tags: ['rice', 'nitrogen', 'lcc'] },
    { title: 'Grape Cultivation — Year-Round Care Calendar', content: 'Jan-Feb: Pruning (October pruning for main crop). Mar-Apr: Berry development — apply potash, gibberellic acid for size. May-Jun: Harvest season — grade, pack, market. Jul-Aug: Back pruning, monsoon — fungicide spray for downy mildew. Sep-Oct: Foundation pruning — apply FYM 10kg/vine. Nov-Dec: Cane maturity — reduce irrigation. Critical: maintain canopy management through shoot positioning. Grape bunches need 55-60 days from flower to harvest. Indian table grapes (Thompson Seedless) fetch best prices in February export window.', category: 'best_practice', cropTypes: ['Grape'], season: 'all', states: ['Maharashtra'], source: 'NRC Grapes Pune', tags: ['grape', 'calendar', 'management'] },
    { title: 'Organic Certification Process in India', content: 'Get organic certification under NPOP (National Programme for Organic Production): 1) Register with accredited certifying body (APEDA list). 2) Conversion period: 2-3 years of organic practices. 3) Maintain farm diary — all inputs, operations, sales. 4) Annual inspection by certifier. 5) No synthetic chemicals allowed. 6) Buffer zone 7.5m from conventional farm. 7) Cost: ₹5,000-15,000/year. Alternative: PGS-India (Participatory Guarantee System) — group certification for domestic market, lower cost. Premium: organic produce sells at 20-40% higher.', category: 'general', season: 'all', source: 'APEDA', tags: ['organic', 'certification', 'npop'] },
    { title: 'Climate-Smart Agriculture Practices', content: 'Adapt to changing climate: 1) Drought-proofing: mulching, zero tillage, rainwater harvesting. 2) Flood resilience: raised bed farming, submergence-tolerant rice (Swarna-Sub1). 3) Heat tolerance: use heat-tolerant wheat (HD 3086), shift sowing dates. 4) Carbon sequestration: agroforestry, conservation agriculture, biochar application. 5) Reduce methane from paddy: alternate wetting and drying (AWD) irrigation saves 30% water and reduces CH4 by 48%. 6) Diversify: integrate crops + livestock + fish for income stability.', category: 'best_practice', season: 'all', source: 'ICAR-CRIDA', tags: ['climate', 'smart', 'adaptation'] },
    { title: 'Mango Export Quality Standards', content: 'Meet export standards for mango: Varieties in demand — Alphonso, Kesar, Dasheri, Langra. Color uniformity 75%+, no blemishes, fruit weight 200-350g. Pre-harvest: spray calcium chloride 1% twice for shelf life. Harvest at 80% maturity (shoulder development). Hot water treatment 48°C for 60 min (quarantine). Pack in CFB boxes with newspaper cushioning. Cool chain: pre-cool to 12°C within 6 hours. Ship by air/sea reefer. Residue limits: follow EU MRL standards. Certificates needed: phytosanitary, organic (if applicable), APEDA registration.', category: 'market', cropTypes: ['Mango'], season: 'kharif', source: 'APEDA', tags: ['mango', 'export', 'quality'] },
];

export async function runSeed() {
    const count = await Advisory.countDocuments();
    if (count > 0) {
        console.log(`⏭  Advisories already seeded (${count} records). Skipping.`);
        return count;
    }
    await Advisory.insertMany(advisories);
    console.log(`✅ Seeded ${advisories.length} advisories`);
    return advisories.length;
}

if (process.argv[1]?.includes('seedAdvisories')) {
    try { await mongoose.connect(process.env.MONGODB_URI); await runSeed(); process.exit(0); }
    catch (err) { console.error(err); process.exit(1); }
}
